---
output: 
  pdf_document:
    keep_tex: yes
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = F, cache = F)
library(tidyverse)
library(kableExtra)
library(latex2exp)
library(viridis)
theme_set(theme_bw())
```

# S1_sim_corr


```{r tab:sim_corr_1, results='asis'}
supp_name <- "corr"
lab <- str_glue("sim_{supp_name}_1")
cap <- str_glue("Simulation results for highly correlated covariates.")
ft <- "Note: The numbers in brackets are the corresponding standard errors estimated using the bootstrap with 500 replications. Bias, SD, RMSE, CP, Length, and their standard errors are multiplied by 100."
n_method <- 8

load(str_glue("../data/setups_{supp_name}.RData"))

# .x <- 1
tab <- map_dfr(1:5, ~{
  load(file = str_glue("../output/{supp_name}_sum_c{.x}.RData"))
  sum_tab %>% 
    left_join(setups, by = "case") %>% 
    arrange(estimator) %>% 
    mutate(
      across(c(bias, sd, rmse, cp, length), ~ sprintf("%.1f", round(.x * 100, 1))),
      across(ends_with("_se"), ~ sprintf("%.1f", round(.x * 100, 1))),
    ) %>% 
    mutate(
      Scenario = case_when(
        strata == "none" & propensity == "eq" ~ "No block",
        strata == "several large coarse" & propensity == "eq" ~ "Large, equal",
        strata == "several large coarse" & propensity == "uneq" ~ "Large, unequal",
        strata == "many small coarse" & propensity == "eq" ~ "Small, equal",
        strata == "many small coarse" & propensity == "uneq" ~ "Small, unequal",
        strata == "hybrid coarse" & propensity == "eq" ~ "Hybrid, equal",
        strata == "hybrid coarse" & propensity == "uneq" ~ "Hybrid, unequal",
        strata == "triplet" & propensity == "eq" ~ "Triplet, equal",
        strata == "triplet" & propensity == "uneq" ~ "Triplet, unequal"
      ),
      `Rerand.` = rerand, 
      `Est.` = fct_recode(estimator, lasso = "lasso.1se", ridge = "ridge.1se", enet = "enet.1se"),
      Bias = str_glue("{bias} ({bias_se})"),
      #`B/S%` = `b/s%`,
      SD = str_glue("{sd} ({sd_se})"),
      #`SD%` = `sd%`,
      RMSE = str_glue("{rmse} ({rmse_se})"),
      CP = str_glue("{cp} ({cp_se})"),
      Length = str_glue("{length} ({length_se})"),
      #`L%` = round(`length%`), 
      `$\\hat{s}$` = round(shat),
      .keep = "none",
      .before = everything()
    )
})

tab %>% 
  kbl(
    label = lab, caption = cap, centering = T,  booktabs = T,
    linesep = "",
    align = c(rep("c", 3), rep("r", ncol(tab) - 3)),
    position = "H", escape = F
  ) %>%
  kable_styling() %>% 
  row_spec(0, align = "c") %>% 
  column_spec(1, width = "1.4cm") %>% 
  collapse_rows(columns = 1, latex_hline = "none") %>% 
  row_spec(n_method, hline_after = T) %>% 
  row_spec(n_method * 2, hline_after = T) %>% 
  row_spec(n_method * 3, hline_after = T) %>% 
  row_spec(n_method * 4, hline_after = T) %>% 
  footnote(general = ft, general_title = "", threeparttable = T)
```



```{r tab:sim_corr_2, results='asis'}
supp_name <- "corr"
lab <- str_glue("sim_{supp_name}_2")
cap <- str_glue("Simulation results for highly correlated covariates.")
ft <- "Note: The numbers in brackets are the corresponding standard errors estimated using the bootstrap with 500 replications. Bias, SD, RMSE, CP, Length, and their standard errors are multiplied by 100."
n_method <- 8

load(str_glue("../data/setups_{supp_name}.RData"))

# .x <- 1
tab <- map_dfr(6:9, ~{
  load(file = str_glue("../output/{supp_name}_sum_c{.x}.RData"))
  sum_tab %>% 
    left_join(setups, by = "case") %>% 
    arrange(estimator) %>% 
    mutate(
      across(c(bias, sd, rmse, cp, length), ~ sprintf("%.1f", round(.x * 100, 1))),
      across(ends_with("_se"), ~ sprintf("%.1f", round(.x * 100, 1))),
    ) %>% 
    mutate(
      Scenario = case_when(
        strata == "none" & propensity == "eq" ~ "No block",
        strata == "several large coarse" & propensity == "eq" ~ "Large, equal",
        strata == "several large coarse" & propensity == "uneq" ~ "Large, unequal",
        strata == "many small coarse" & propensity == "eq" ~ "Small, equal",
        strata == "many small coarse" & propensity == "uneq" ~ "Small, unequal",
        strata == "hybrid coarse" & propensity == "eq" ~ "Hybrid, equal",
        strata == "hybrid coarse" & propensity == "uneq" ~ "Hybrid, unequal",
        strata == "triplet" & propensity == "eq" ~ "Triplet, equal",
        strata == "triplet" & propensity == "uneq" ~ "Triplet, unequal"
      ),
      `Rerand.` = rerand, 
      `Est.` = fct_recode(estimator, lasso = "lasso.1se", ridge = "ridge.1se", enet = "enet.1se"),
      Bias = str_glue("{bias} ({bias_se})"),
      #`B/S%` = `b/s%`,
      SD = str_glue("{sd} ({sd_se})"),
      #`SD%` = `sd%`,
      RMSE = str_glue("{rmse} ({rmse_se})"),
      CP = str_glue("{cp} ({cp_se})"),
      Length = str_glue("{length} ({length_se})"),
      #`L%` = round(`length%`), 
      `$\\hat{s}$` = round(shat),
      .keep = "none",
      .before = everything()
    )
})

tab %>% 
  kbl(
    label = lab, caption = cap, centering = T,  booktabs = T,
    linesep = "",
    align = c(rep("c", 3), rep("r", ncol(tab) - 3)),
    position = "H", escape = F
  ) %>%
  kable_styling() %>% 
  row_spec(0, align = "c") %>% 
  column_spec(1, width = "1.4cm") %>%
  collapse_rows(columns = 1, latex_hline = "none") %>% 
  row_spec(n_method, hline_after = T) %>% 
  row_spec(n_method * 2, hline_after = T) %>% 
  row_spec(n_method * 3, hline_after = T) %>% 
  footnote(general = ft, general_title = "", threeparttable = T)
```


# S2_sim_dense


```{r tab:sim_dense_40_1, results='asis'}
supp_name <- "dense"
lab <- str_glue("sim_{supp_name}_40_1")
cap <- str_glue("Simulation results for Lasso, ridge, and elastic net, when $s=40$.")
ft <- "Note: The numbers in brackets are the corresponding standard errors estimated using the bootstrap with 500 replications. Bias, SD, RMSE, CP, Length, and their standard errors are multiplied by 100."
n_method <- 8

load(str_glue("../data/setups_{supp_name}.RData"))

# .x <- 1
tab <- map_dfr(1:5, ~{
  load(file = str_glue("../output/{supp_name}_sum_c{.x}.RData"))
  sum_tab %>% 
    left_join(setups, by = "case") %>% 
    filter(s == 40) %>% 
    arrange(estimator) %>% 
    mutate(
      across(c(bias, sd, rmse, cp, length), ~ sprintf("%.1f", round(.x * 100, 1))),
      across(ends_with("_se"), ~ sprintf("%.1f", round(.x * 100, 1))),
    ) %>% 
    mutate(
      Scenario = case_when(
        strata == "none" & propensity == "eq" ~ "No block",
        strata == "several large coarse" & propensity == "eq" ~ "Large, equal",
        strata == "several large coarse" & propensity == "uneq" ~ "Large, unequal",
        strata == "many small coarse" & propensity == "eq" ~ "Small, equal",
        strata == "many small coarse" & propensity == "uneq" ~ "Small, unequal",
        strata == "hybrid coarse" & propensity == "eq" ~ "Hybrid, equal",
        strata == "hybrid coarse" & propensity == "uneq" ~ "Hybrid, unequal",
        strata == "triplet" & propensity == "eq" ~ "Triplet, equal",
        strata == "triplet" & propensity == "uneq" ~ "Triplet, unequal"
      ),
      `Rerand.` = rerand, 
      `Est.` = fct_recode(estimator, lasso = "lasso.1se", ridge = "ridge.1se", enet = "enet.1se"),
      Bias = str_glue("{bias} ({bias_se})"),
      #`B/S%` = `b/s%`,
      SD = str_glue("{sd} ({sd_se})"),
      #`SD%` = `sd%`,
      RMSE = str_glue("{rmse} ({rmse_se})"),
      CP = str_glue("{cp} ({cp_se})"),
      Length = str_glue("{length} ({length_se})"),
      #`L%` = round(`length%`), 
      `$\\hat{s}$` = round(shat),
      .keep = "none",
      .before = everything()
    )
})

tab %>% 
  kbl(
    label = lab, caption = cap, centering = T,  booktabs = T, linesep = "",
    align = c(rep("c", 3), rep("r", ncol(tab) - 3)),
    position = "H", escape = F
  ) %>%
  kable_styling() %>% 
  row_spec(0, align = "c") %>% 
  column_spec(1, width = "1.4cm") %>% 
  collapse_rows(columns = 1, latex_hline = "none") %>% 
  row_spec(n_method, hline_after = T) %>% 
  row_spec(n_method * 2, hline_after = T) %>% 
  row_spec(n_method * 3, hline_after = T) %>% 
  row_spec(n_method * 4, hline_after = T) %>% 
  footnote(general = ft, general_title = "", threeparttable = T)
```


```{r tab:sim_dense_40_2, results='asis'}
supp_name <- "dense"
lab <- str_glue("sim_{supp_name}_40_2")
cap <- str_glue("Simulation results for Lasso, ridge, and elastic net, when $s=40$.")
ft <- "Note: The numbers in brackets are the corresponding standard errors estimated using the bootstrap with 500 replications. Bias, SD, RMSE, CP, Length, and their standard errors are multiplied by 100."
n_method <- 8

load(str_glue("../data/setups_{supp_name}.RData"))

# .x <- 1
tab <- map_dfr(6:9, ~{
  load(file = str_glue("../output/{supp_name}_sum_c{.x}.RData"))
  sum_tab %>% 
    left_join(setups, by = "case") %>% 
    filter(s == 40) %>% 
    arrange(estimator) %>% 
    mutate(
      across(c(bias, sd, rmse, cp, length), ~ sprintf("%.1f", round(.x * 100, 1))),
      across(ends_with("_se"), ~ sprintf("%.1f", round(.x * 100, 1))),
    ) %>% 
    mutate(
      Scenario = case_when(
        strata == "none" & propensity == "eq" ~ "No block",
        strata == "several large coarse" & propensity == "eq" ~ "Large, equal",
        strata == "several large coarse" & propensity == "uneq" ~ "Large, unequal",
        strata == "many small coarse" & propensity == "eq" ~ "Small, equal",
        strata == "many small coarse" & propensity == "uneq" ~ "Small, unequal",
        strata == "hybrid coarse" & propensity == "eq" ~ "Hybrid, equal",
        strata == "hybrid coarse" & propensity == "uneq" ~ "Hybrid, unequal",
        strata == "triplet" & propensity == "eq" ~ "Triplet, equal",
        strata == "triplet" & propensity == "uneq" ~ "Triplet, unequal"
      ),
      `Rerand.` = rerand, 
      `Est.` = fct_recode(estimator, lasso = "lasso.1se", ridge = "ridge.1se", enet = "enet.1se"),
      Bias = str_glue("{bias} ({bias_se})"),
      #`B/S%` = `b/s%`,
      SD = str_glue("{sd} ({sd_se})"),
      #`SD%` = `sd%`,
      RMSE = str_glue("{rmse} ({rmse_se})"),
      CP = str_glue("{cp} ({cp_se})"),
      Length = str_glue("{length} ({length_se})"),
      #`L%` = round(`length%`), 
      `$\\hat{s}$` = round(shat),
      .keep = "none",
      .before = everything()
    )
})

tab %>% 
  kbl(
    label = lab, caption = cap, centering = T,  booktabs = T, linesep = "",
    align = c(rep("c", 3), rep("r", ncol(tab) - 3)),
    position = "H", escape = F
  ) %>%
  kable_styling() %>% 
  row_spec(0, align = "c") %>% 
  column_spec(1, width = "1.4cm") %>% 
  collapse_rows(columns = 1, latex_hline = "none") %>% 
  row_spec(n_method, hline_after = T) %>% 
  row_spec(n_method * 2, hline_after = T) %>% 
  row_spec(n_method * 3, hline_after = T) %>% 
  footnote(general = ft, general_title = "", threeparttable = T)
```



```{r tab:sim_dense_200_1, results='asis'}
supp_name <- "dense"
lab <- str_glue("sim_{supp_name}_200_1")
cap <- str_glue("Simulation results for Lasso, ridge, and elastic net, when $s=200$.")
ft <- "Note: The numbers in brackets are the corresponding standard errors estimated using the bootstrap with 500 replications. Bias, SD, RMSE, CP, Length, and their standard errors are multiplied by 100."
n_method <- 8

load(str_glue("../data/setups_{supp_name}.RData"))

# .x <- 1
tab <- map_dfr(10:14, ~{
  load(file = str_glue("../output/{supp_name}_sum_c{.x}.RData"))
  sum_tab %>% 
    left_join(setups, by = "case") %>% 
    filter(s == 200) %>% 
    arrange(estimator) %>% 
    mutate(
      across(c(bias, sd, rmse, cp, length), ~ sprintf("%.1f", round(.x * 100, 1))),
      across(ends_with("_se"), ~ sprintf("%.1f", round(.x * 100, 1))),
    ) %>% 
    mutate(
      Scenario = case_when(
        strata == "none" & propensity == "eq" ~ "No block",
        strata == "several large coarse" & propensity == "eq" ~ "Large, equal",
        strata == "several large coarse" & propensity == "uneq" ~ "Large, unequal",
        strata == "many small coarse" & propensity == "eq" ~ "Small, equal",
        strata == "many small coarse" & propensity == "uneq" ~ "Small, unequal",
        strata == "hybrid coarse" & propensity == "eq" ~ "Hybrid, equal",
        strata == "hybrid coarse" & propensity == "uneq" ~ "Hybrid, unequal",
        strata == "triplet" & propensity == "eq" ~ "Triplet, equal",
        strata == "triplet" & propensity == "uneq" ~ "Triplet, unequal"
      ),
      `Rerand.` = rerand, 
      `Est.` = fct_recode(estimator, lasso = "lasso.1se", ridge = "ridge.1se", enet = "enet.1se"),
      Bias = str_glue("{bias} ({bias_se})"),
      #`B/S%` = `b/s%`,
      SD = str_glue("{sd} ({sd_se})"),
      #`SD%` = `sd%`,
      RMSE = str_glue("{rmse} ({rmse_se})"),
      CP = str_glue("{cp} ({cp_se})"),
      Length = str_glue("{length} ({length_se})"),
      #`L%` = round(`length%`), 
      `$\\hat{s}$` = round(shat),
      .keep = "none",
      .before = everything()
    )
})

tab %>% 
  kbl(
    label = lab, caption = cap, centering = T,  booktabs = T, linesep = "",
    align = c(rep("c", 3), rep("r", ncol(tab) - 3)),
    position = "H", escape = F
  ) %>%
  kable_styling() %>% 
  row_spec(0, align = "c") %>% 
  column_spec(1, width = "1.4cm") %>% 
  collapse_rows(columns = 1, latex_hline = "none") %>% 
  row_spec(n_method, hline_after = T) %>% 
  row_spec(n_method * 2, hline_after = T) %>% 
  row_spec(n_method * 3, hline_after = T) %>% 
  row_spec(n_method * 4, hline_after = T) %>% 
  footnote(general = ft, general_title = "", threeparttable = T)
```


```{r tab:sim_dense_200_2, results='asis'}
supp_name <- "dense"
lab <- str_glue("sim_{supp_name}_200_2")
cap <- str_glue("Simulation results for Lasso, ridge, and elastic net, when $s=200$.")
ft <- "Note: The numbers in brackets are the corresponding standard errors estimated using the bootstrap with 500 replications. Bias, SD, RMSE, CP, Length, and their standard errors are multiplied by 100."
n_method <- 8

load(str_glue("../data/setups_{supp_name}.RData"))

# .x <- 1
tab <- map_dfr(15:18, ~{
  load(file = str_glue("../output/{supp_name}_sum_c{.x}.RData"))
  sum_tab %>% 
    left_join(setups, by = "case") %>% 
    filter(s == 200) %>% 
    arrange(estimator) %>% 
    mutate(
      across(c(bias, sd, rmse, cp, length), ~ sprintf("%.1f", round(.x * 100, 1))),
      across(ends_with("_se"), ~ sprintf("%.1f", round(.x * 100, 1))),
    ) %>% 
    mutate(
      Scenario = case_when(
        strata == "none" & propensity == "eq" ~ "No block",
        strata == "several large coarse" & propensity == "eq" ~ "Large, equal",
        strata == "several large coarse" & propensity == "uneq" ~ "Large, unequal",
        strata == "many small coarse" & propensity == "eq" ~ "Small, equal",
        strata == "many small coarse" & propensity == "uneq" ~ "Small, unequal",
        strata == "hybrid coarse" & propensity == "eq" ~ "Hybrid, equal",
        strata == "hybrid coarse" & propensity == "uneq" ~ "Hybrid, unequal",
        strata == "triplet" & propensity == "eq" ~ "Triplet, equal",
        strata == "triplet" & propensity == "uneq" ~ "Triplet, unequal"
      ),
      `Rerand.` = rerand, 
      `Est.` = fct_recode(estimator, lasso = "lasso.1se", ridge = "ridge.1se", enet = "enet.1se"),
      Bias = str_glue("{bias} ({bias_se})"),
      #`B/S%` = `b/s%`,
      SD = str_glue("{sd} ({sd_se})"),
      #`SD%` = `sd%`,
      RMSE = str_glue("{rmse} ({rmse_se})"),
      CP = str_glue("{cp} ({cp_se})"),
      Length = str_glue("{length} ({length_se})"),
      #`L%` = round(`length%`), 
      `$\\hat{s}$` = round(shat),
      .keep = "none",
      .before = everything()
    )
})

tab %>% 
  kbl(
    label = lab, caption = cap, centering = T,  booktabs = T, linesep = "",
    align = c(rep("c", 3), rep("r", ncol(tab) - 3)),
    position = "H", escape = F
  ) %>%
  kable_styling() %>% 
  row_spec(0, align = "c") %>% 
  column_spec(1, width = "1.4cm") %>% 
  collapse_rows(columns = 1, latex_hline = "none") %>% 
  row_spec(n_method, hline_after = T) %>% 
  row_spec(n_method * 2, hline_after = T) %>% 
  row_spec(n_method * 3, hline_after = T) %>% 
  footnote(general = ft, general_title = "", threeparttable = T)
```


```{r tab:sim_dense_400_1, results='asis'}
supp_name <- "dense"
lab <- str_glue("sim_{supp_name}_400_1")
cap <- str_glue("Simulation results for Lasso, ridge, and elastic net, when $s=400$.")
ft <- "Note: The numbers in brackets are the corresponding standard errors estimated using the bootstrap with 500 replications. Bias, SD, RMSE, CP, Length, and their standard errors are multiplied by 100."
n_method <- 8

load(str_glue("../data/setups_{supp_name}.RData"))

# .x <- 1
tab <- map_dfr(19:23, ~{
  load(file = str_glue("../output/{supp_name}_sum_c{.x}.RData"))
  sum_tab %>% 
    left_join(setups, by = "case") %>% 
    filter(s == 400) %>% 
    arrange(estimator) %>% 
    mutate(
      across(c(bias, sd, rmse, cp, length), ~ sprintf("%.1f", round(.x * 100, 1))),
      across(ends_with("_se"), ~ sprintf("%.1f", round(.x * 100, 1))),
    ) %>% 
    mutate(
      Scenario = case_when(
        strata == "none" & propensity == "eq" ~ "No block",
        strata == "several large coarse" & propensity == "eq" ~ "Large, equal",
        strata == "several large coarse" & propensity == "uneq" ~ "Large, unequal",
        strata == "many small coarse" & propensity == "eq" ~ "Small, equal",
        strata == "many small coarse" & propensity == "uneq" ~ "Small, unequal",
        strata == "hybrid coarse" & propensity == "eq" ~ "Hybrid, equal",
        strata == "hybrid coarse" & propensity == "uneq" ~ "Hybrid, unequal",
        strata == "triplet" & propensity == "eq" ~ "Triplet, equal",
        strata == "triplet" & propensity == "uneq" ~ "Triplet, unequal"
      ),
      `Rerand.` = rerand, 
      `Est.` = fct_recode(estimator, lasso = "lasso.1se", ridge = "ridge.1se", enet = "enet.1se"),
      Bias = str_glue("{bias} ({bias_se})"),
      #`B/S%` = `b/s%`,
      SD = str_glue("{sd} ({sd_se})"),
      #`SD%` = `sd%`,
      RMSE = str_glue("{rmse} ({rmse_se})"),
      CP = str_glue("{cp} ({cp_se})"),
      Length = str_glue("{length} ({length_se})"),
      #`L%` = round(`length%`), 
      `$\\hat{s}$` = round(shat),
      .keep = "none",
      .before = everything()
    )
})

tab %>% 
  kbl(
    label = lab, caption = cap, centering = T,  booktabs = T, linesep = "",
    align = c(rep("c", 3), rep("r", ncol(tab) - 3)),
    position = "H", escape = F
  ) %>%
  kable_styling() %>% 
  row_spec(0, align = "c") %>% 
  column_spec(1, width = "1.4cm") %>% 
  collapse_rows(columns = 1, latex_hline = "none") %>% 
  row_spec(n_method, hline_after = T) %>% 
  row_spec(n_method * 2, hline_after = T) %>% 
  row_spec(n_method * 3, hline_after = T) %>% 
  row_spec(n_method * 4, hline_after = T) %>% 
  footnote(general = ft, general_title = "", threeparttable = T)
```

```{r tab:sim_dense_400_2, results='asis'}
supp_name <- "dense"
lab <- str_glue("sim_{supp_name}_400_2")
cap <- str_glue("Simulation results for Lasso, ridge, and elastic net, when $s=400$.")
ft <- "Note: The numbers in brackets are the corresponding standard errors estimated using the bootstrap with 500 replications. Bias, SD, RMSE, CP, Length, and their standard errors are multiplied by 100."
n_method <- 8

load(str_glue("../data/setups_{supp_name}.RData"))

# .x <- 1
tab <- map_dfr(24:27, ~{
  load(file = str_glue("../output/{supp_name}_sum_c{.x}.RData"))
  sum_tab %>% 
    left_join(setups, by = "case") %>% 
    filter(s == 400) %>% 
    arrange(estimator) %>% 
    mutate(
      across(c(bias, sd, rmse, cp, length), ~ sprintf("%.1f", round(.x * 100, 1))),
      across(ends_with("_se"), ~ sprintf("%.1f", round(.x * 100, 1))),
    ) %>% 
    mutate(
      Scenario = case_when(
        strata == "none" & propensity == "eq" ~ "No block",
        strata == "several large coarse" & propensity == "eq" ~ "Large, equal",
        strata == "several large coarse" & propensity == "uneq" ~ "Large, unequal",
        strata == "many small coarse" & propensity == "eq" ~ "Small, equal",
        strata == "many small coarse" & propensity == "uneq" ~ "Small, unequal",
        strata == "hybrid coarse" & propensity == "eq" ~ "Hybrid, equal",
        strata == "hybrid coarse" & propensity == "uneq" ~ "Hybrid, unequal",
        strata == "triplet" & propensity == "eq" ~ "Triplet, equal",
        strata == "triplet" & propensity == "uneq" ~ "Triplet, unequal"
      ),
      `Rerand.` = rerand, 
      `Est.` = fct_recode(estimator, lasso = "lasso.1se", ridge = "ridge.1se", enet = "enet.1se"),
      Bias = str_glue("{bias} ({bias_se})"),
      #`B/S%` = `b/s%`,
      SD = str_glue("{sd} ({sd_se})"),
      #`SD%` = `sd%`,
      RMSE = str_glue("{rmse} ({rmse_se})"),
      CP = str_glue("{cp} ({cp_se})"),
      Length = str_glue("{length} ({length_se})"),
      #`L%` = round(`length%`), 
      `$\\hat{s}$` = round(shat),
      .keep = "none",
      .before = everything()
    )
})

tab %>% 
  kbl(
    label = lab, caption = cap, centering = T,  booktabs = T, linesep = "",
    align = c(rep("c", 3), rep("r", ncol(tab) - 3)),
    position = "H", escape = F
  ) %>%
  kable_styling() %>% 
  row_spec(0, align = "c") %>% 
  column_spec(1, width = "1.4cm") %>% 
  collapse_rows(columns = 1, latex_hline = "none") %>% 
  row_spec(n_method, hline_after = T) %>% 
  row_spec(n_method * 2, hline_after = T) %>% 
  row_spec(n_method * 3, hline_after = T) %>% 
  footnote(general = ft, general_title = "", threeparttable = T)
```



# S3_sim_bias


```{r fig:sim_bias, fig.width=12, fig.height=6, fig.show = 'asis'}
supp_name <- "bias"
load(str_glue("../data/setups_dense.RData"))

# .x <- 2
tab <- map_dfr(1:27, ~{
  load(file = str_glue("../output/{supp_name}_sum_c{.x}.RData"))
  sum_tab %>% 
    left_join(setups, by = "case") %>% 
    mutate(
      Scenario = case_when(
        strata == "none" & propensity == "eq" ~ "No block",
        strata == "several large coarse" & propensity == "eq" ~ "Large, equal",
        strata == "several large coarse" & propensity == "uneq" ~ "Large, unequal",
        strata == "many small coarse" & propensity == "eq" ~ "Small, equal",
        strata == "many small coarse" & propensity == "uneq" ~ "Small, unequal",
        strata == "hybrid coarse" & propensity == "eq" ~ "Hybrid, equal",
        strata == "hybrid coarse" & propensity == "uneq" ~ "Hybrid, unequal",
        strata == "triplet" & propensity == "eq" ~ "Triplet, equal",
        strata == "triplet" & propensity == "uneq" ~ "Triplet, unequal"
      ),
      `Rerand` = rerand, 
      `Estimator` = fct_recode(estimator, lasso = "lasso.1se",
                               "lasso+ols" = "lasso+ols.1se"),
      # Bias = str_glue("{bias} ({bias_se})"),
      Bias = bias,
      `B/S%` = `b/s%`,
      #SD = str_glue("{sd} ({sd_se})"),
      SD = sd,
      `SD%` = `sd%`,
      #RMSE = str_glue("{rmse} ({rmse_se})"),
      RMSE = rmse,
      #CP = str_glue("{cp} ({cp_se})"),
      CP = cp,
      #Length = str_glue("{length} ({length_se})"),
      Length = length,
      `L%` = round(`length%`), 
      shat = round(shat),
      s = s,
      .keep = "none",
      .before = everything()
    )
}) %>% mutate(Scenario = as_factor(Scenario))

tab %>% 
  mutate(`Absolute bias` = abs(Bias)) %>% 
  ggplot(aes(x = s, y = `Absolute bias`, color = Estimator)) +
  geom_line() +
  geom_point() +
  facet_grid(Rerand ~ Scenario, labeller = labeller(.rows = label_both, .cols = label_value)) +
  xlab(latex2exp::TeX("$s$")) 
ggsave(filename = "sim_bias.pdf", width = 12, height = 6)
```



```{r tab:sim_bias_40_1, results='asis'}
supp_name <- "bias"
lab <- str_glue("sim_{supp_name}_40_1")
cap <- str_glue("Simulation results for OLS, Lasso, and Lasso + OLS, when $s=40$.")
ft <- "Note: The numbers in brackets are the corresponding standard errors estimated using the bootstrap with 500 replications. Bias, SD, RMSE, CP, Length, and their standard errors are multiplied by 100."
n_method <- 8

load(str_glue("../data/setups_dense.RData"))

# .x <- 2
tab <- map_dfr(1:5, ~{
  load(file = str_glue("../output/{supp_name}_sum_c{.x}.RData"))
  sum_tab %>% 
    left_join(setups, by = "case") %>% 
    filter(s == 40) %>% 
    arrange(estimator) %>% 
    mutate(
      bias = sprintf("%.3f", round(bias * 100, 3)),
      across(c(sd, rmse, cp, length), ~ sprintf("%.1f", round(.x * 100, 1))),
      across(ends_with("_se") & !bias_se, ~ sprintf("%.1f", round(.x * 100, 1))),
      across(bias_se, ~ sprintf("%.3f", round(.x * 100, 3)))
    ) %>% 
    mutate(
      Scenario = case_when(
        strata == "none" & propensity == "eq" ~ "No block",
        strata == "several large coarse" & propensity == "eq" ~ "Large, equal",
        strata == "several large coarse" & propensity == "uneq" ~ "Large, unequal",
        strata == "many small coarse" & propensity == "eq" ~ "Small, equal",
        strata == "many small coarse" & propensity == "uneq" ~ "Small, unequal",
        strata == "hybrid coarse" & propensity == "eq" ~ "Hybrid, equal",
        strata == "hybrid coarse" & propensity == "uneq" ~ "Hybrid, unequal",
        strata == "triplet" & propensity == "eq" ~ "Triplet, equal",
        strata == "triplet" & propensity == "uneq" ~ "Triplet, unequal"
      ),
      `Rerand.` = rerand, 
      `Est.` = fct_recode(estimator, lasso = "lasso.1se", "lasso+ols" = "lasso+ols.1se"),
      Bias = str_glue("{bias} ({bias_se})"),
      #`B/S%` = `b/s%`,
      SD = str_glue("{sd} ({sd_se})"),
      #`SD%` = `sd%`,
      RMSE = str_glue("{rmse} ({rmse_se})"),
      CP = str_glue("{cp} ({cp_se})"),
      Length = str_glue("{length} ({length_se})"),
      #`L%` = round(`length%`), 
      #`$\\hat{s}$` = round(shat),
      .keep = "none",
      .before = everything()
    )
})

tab %>% 
  kbl(
    label = lab, caption = cap, centering = T,  booktabs = T, linesep = "",
    align = c(rep("c", 3), rep("r", ncol(tab) - 3)),
    position = "H", escape = F
  ) %>%
  kable_styling() %>% 
  row_spec(0, align = "c") %>% 
  column_spec(1, width = "1.4cm") %>% 
  collapse_rows(columns = 1, latex_hline = "none") %>% 
  row_spec(n_method, hline_after = T) %>% 
  row_spec(n_method * 2, hline_after = T) %>% 
  row_spec(n_method * 3, hline_after = T) %>% 
  row_spec(n_method * 4, hline_after = T) %>% 
  footnote(general = ft, general_title = "", threeparttable = T)
```



```{r tab:sim_bias_40_2, results='asis'}
supp_name <- "bias"
lab <- str_glue("sim_{supp_name}_40_2")
cap <- str_glue("Simulation results for OLS, Lasso, and Lasso + OLS, when $s=40$.")
ft <- "Note: The numbers in brackets are the corresponding standard errors estimated using the bootstrap with 500 replications. Bias, SD, RMSE, CP, Length, and their standard errors are multiplied by 100."
n_method <- 8

load(str_glue("../data/setups_dense.RData"))

# .x <- 2
tab <- map_dfr(6:9, ~{
  load(file = str_glue("../output/{supp_name}_sum_c{.x}.RData"))
  sum_tab %>% 
    left_join(setups, by = "case") %>% 
    filter(s == 40) %>% 
    arrange(estimator) %>% 
    mutate(
      bias = sprintf("%.3f", round(bias * 100, 3)),
      across(c(sd, rmse, cp, length), ~ sprintf("%.1f", round(.x * 100, 1))),
      across(ends_with("_se") & !bias_se, ~ sprintf("%.1f", round(.x * 100, 1))),
      across(bias_se, ~ sprintf("%.3f", round(.x * 100, 3)))
    ) %>% 
    mutate(
      Scenario = case_when(
        strata == "none" & propensity == "eq" ~ "No block",
        strata == "several large coarse" & propensity == "eq" ~ "Large, equal",
        strata == "several large coarse" & propensity == "uneq" ~ "Large, unequal",
        strata == "many small coarse" & propensity == "eq" ~ "Small, equal",
        strata == "many small coarse" & propensity == "uneq" ~ "Small, unequal",
        strata == "hybrid coarse" & propensity == "eq" ~ "Hybrid, equal",
        strata == "hybrid coarse" & propensity == "uneq" ~ "Hybrid, unequal",
        strata == "triplet" & propensity == "eq" ~ "Triplet, equal",
        strata == "triplet" & propensity == "uneq" ~ "Triplet, unequal"
      ),
      `Rerand.` = rerand, 
      `Est.` = fct_recode(estimator, lasso = "lasso.1se", "lasso+ols" = "lasso+ols.1se"),
      Bias = str_glue("{bias} ({bias_se})"),
      #`B/S%` = `b/s%`,
      SD = str_glue("{sd} ({sd_se})"),
      #`SD%` = `sd%`,
      RMSE = str_glue("{rmse} ({rmse_se})"),
      CP = str_glue("{cp} ({cp_se})"),
      Length = str_glue("{length} ({length_se})"),
      #`L%` = round(`length%`), 
      #`$\\hat{s}$` = round(shat),
      .keep = "none",
      .before = everything()
    )
})

tab %>% 
  kbl(
    label = lab, caption = cap, centering = T,  booktabs = T, linesep = "",
    align = c(rep("c", 3), rep("r", ncol(tab) - 3)),
    position = "H", escape = F
  ) %>%
  kable_styling() %>% 
  row_spec(0, align = "c") %>% 
  column_spec(1, width = "1.4cm") %>% 
  collapse_rows(columns = 1, latex_hline = "none") %>% 
  row_spec(n_method, hline_after = T) %>% 
  row_spec(n_method * 2, hline_after = T) %>% 
  row_spec(n_method * 3, hline_after = T) %>% 
  footnote(general = ft, general_title = "", threeparttable = T)
```


```{r tab:sim_bias_200_1, results='asis'}
supp_name <- "bias"
lab <- str_glue("sim_{supp_name}_200_1")
cap <- str_glue("Simulation results for OLS, Lasso, and Lasso + OLS, when $s=200$.")
ft <- "Note: The numbers in brackets are the corresponding standard errors estimated using the bootstrap with 500 replications. Bias, SD, RMSE, CP, Length, and their standard errors are multiplied by 100."
n_method <- 8

load(str_glue("../data/setups_dense.RData"))

# .x <- 2
tab <- map_dfr(10:14, ~{
  load(file = str_glue("../output/{supp_name}_sum_c{.x}.RData"))
  sum_tab %>% 
    left_join(setups, by = "case") %>% 
    filter(s == 200) %>% 
    arrange(estimator) %>% 
    mutate(
      bias = sprintf("%.3f", round(bias * 100, 3)),
      across(c(sd, rmse, cp, length), ~ sprintf("%.1f", round(.x * 100, 1))),
      across(ends_with("_se") & !bias_se, ~ sprintf("%.1f", round(.x * 100, 1))),
      across(bias_se, ~ sprintf("%.3f", round(.x * 100, 3)))
    ) %>% 
    mutate(
      Scenario = case_when(
        strata == "none" & propensity == "eq" ~ "No block",
        strata == "several large coarse" & propensity == "eq" ~ "Large, equal",
        strata == "several large coarse" & propensity == "uneq" ~ "Large, unequal",
        strata == "many small coarse" & propensity == "eq" ~ "Small, equal",
        strata == "many small coarse" & propensity == "uneq" ~ "Small, unequal",
        strata == "hybrid coarse" & propensity == "eq" ~ "Hybrid, equal",
        strata == "hybrid coarse" & propensity == "uneq" ~ "Hybrid, unequal",
        strata == "triplet" & propensity == "eq" ~ "Triplet, equal",
        strata == "triplet" & propensity == "uneq" ~ "Triplet, unequal"
      ),
      `Rerand.` = rerand, 
      `Est.` = fct_recode(estimator, lasso = "lasso.1se", "lasso+ols" = "lasso+ols.1se"),
      Bias = str_glue("{bias} ({bias_se})"),
      #`B/S%` = `b/s%`,
      SD = str_glue("{sd} ({sd_se})"),
      #`SD%` = `sd%`,
      RMSE = str_glue("{rmse} ({rmse_se})"),
      CP = str_glue("{cp} ({cp_se})"),
      Length = str_glue("{length} ({length_se})"),
      #`L%` = round(`length%`), 
      #`$\\hat{s}$` = round(shat),
      .keep = "none",
      .before = everything()
    )
})

tab %>% 
  kbl(
    label = lab, caption = cap, centering = T,  booktabs = T, linesep = "",
    align = c(rep("c", 3), rep("r", ncol(tab) - 3)),
    position = "H", escape = F
  ) %>%
  kable_styling() %>% 
  row_spec(0, align = "c") %>% 
  column_spec(1, width = "1.4cm") %>% 
  collapse_rows(columns = 1, latex_hline = "none") %>% 
  row_spec(n_method, hline_after = T) %>% 
  row_spec(n_method * 2, hline_after = T) %>% 
  row_spec(n_method * 3, hline_after = T) %>% 
  row_spec(n_method * 4, hline_after = T) %>% 
  footnote(general = ft, general_title = "", threeparttable = T)
```



```{r tab:sim_bias_200_2, results='asis'}
supp_name <- "bias"
lab <- str_glue("sim_{supp_name}_200_2")
cap <- str_glue("Simulation results for OLS, Lasso, and Lasso + OLS, when $s=200$.")
ft <- "Note: The numbers in brackets are the corresponding standard errors estimated using the bootstrap with 500 replications. Bias, SD, RMSE, CP, Length, and their standard errors are multiplied by 100."
n_method <- 8

load(str_glue("../data/setups_dense.RData"))

# .x <- 2
tab <- map_dfr(15:18, ~{
  load(file = str_glue("../output/{supp_name}_sum_c{.x}.RData"))
  sum_tab %>% 
    left_join(setups, by = "case") %>% 
    filter(s == 200) %>% 
    arrange(estimator) %>% 
    mutate(
      bias = sprintf("%.3f", round(bias * 100, 3)),
      across(c(sd, rmse, cp, length), ~ sprintf("%.1f", round(.x * 100, 1))),
      across(ends_with("_se") & !bias_se, ~ sprintf("%.1f", round(.x * 100, 1))),
      across(bias_se, ~ sprintf("%.3f", round(.x * 100, 3)))
    ) %>% 
    mutate(
      Scenario = case_when(
        strata == "none" & propensity == "eq" ~ "No block",
        strata == "several large coarse" & propensity == "eq" ~ "Large, equal",
        strata == "several large coarse" & propensity == "uneq" ~ "Large, unequal",
        strata == "many small coarse" & propensity == "eq" ~ "Small, equal",
        strata == "many small coarse" & propensity == "uneq" ~ "Small, unequal",
        strata == "hybrid coarse" & propensity == "eq" ~ "Hybrid, equal",
        strata == "hybrid coarse" & propensity == "uneq" ~ "Hybrid, unequal",
        strata == "triplet" & propensity == "eq" ~ "Triplet, equal",
        strata == "triplet" & propensity == "uneq" ~ "Triplet, unequal"
      ),
      `Rerand.` = rerand, 
      `Est.` = fct_recode(estimator, lasso = "lasso.1se", "lasso+ols" = "lasso+ols.1se"),
      Bias = str_glue("{bias} ({bias_se})"),
      #`B/S%` = `b/s%`,
      SD = str_glue("{sd} ({sd_se})"),
      #`SD%` = `sd%`,
      RMSE = str_glue("{rmse} ({rmse_se})"),
      CP = str_glue("{cp} ({cp_se})"),
      Length = str_glue("{length} ({length_se})"),
      #`L%` = round(`length%`), 
      #`$\\hat{s}$` = round(shat),
      .keep = "none",
      .before = everything()
    )
})

tab %>% 
  kbl(
    label = lab, caption = cap, centering = T,  booktabs = T, linesep = "",
    align = c(rep("c", 3), rep("r", ncol(tab) - 3)),
    position = "H", escape = F
  ) %>%
  kable_styling() %>% 
  row_spec(0, align = "c") %>% 
  column_spec(1, width = "1.4cm") %>% 
  collapse_rows(columns = 1, latex_hline = "none") %>% 
  row_spec(n_method, hline_after = T) %>% 
  row_spec(n_method * 2, hline_after = T) %>% 
  row_spec(n_method * 3, hline_after = T) %>% 
  footnote(general = ft, general_title = "", threeparttable = T)
```


```{r tab:sim_bias_400_1, results='asis'}
supp_name <- "bias"
lab <- str_glue("sim_{supp_name}_400_1")
cap <- str_glue("Simulation results for OLS, Lasso, and Lasso + OLS, when $s=400$.")
ft <- "Note: The numbers in brackets are the corresponding standard errors estimated using the bootstrap with 500 replications. Bias, SD, RMSE, CP, Length, and their standard errors are multiplied by 100."
n_method <- 8

load(str_glue("../data/setups_dense.RData"))

# .x <- 2
tab <- map_dfr(19:23, ~{
  load(file = str_glue("../output/{supp_name}_sum_c{.x}.RData"))
  sum_tab %>% 
    left_join(setups, by = "case") %>% 
    filter(s == 400) %>% 
    arrange(estimator) %>% 
    mutate(
      bias = sprintf("%.3f", round(bias * 100, 3)),
      across(c(sd, rmse, cp, length), ~ sprintf("%.1f", round(.x * 100, 1))),
      across(ends_with("_se") & !bias_se, ~ sprintf("%.1f", round(.x * 100, 1))),
      across(bias_se, ~ sprintf("%.3f", round(.x * 100, 3)))
    ) %>% 
    mutate(
      Scenario = case_when(
        strata == "none" & propensity == "eq" ~ "No block",
        strata == "several large coarse" & propensity == "eq" ~ "Large, equal",
        strata == "several large coarse" & propensity == "uneq" ~ "Large, unequal",
        strata == "many small coarse" & propensity == "eq" ~ "Small, equal",
        strata == "many small coarse" & propensity == "uneq" ~ "Small, unequal",
        strata == "hybrid coarse" & propensity == "eq" ~ "Hybrid, equal",
        strata == "hybrid coarse" & propensity == "uneq" ~ "Hybrid, unequal",
        strata == "triplet" & propensity == "eq" ~ "Triplet, equal",
        strata == "triplet" & propensity == "uneq" ~ "Triplet, unequal"
      ),
      `Rerand.` = rerand, 
      `Est.` = fct_recode(estimator, lasso = "lasso.1se", "lasso+ols" = "lasso+ols.1se"),
      Bias = str_glue("{bias} ({bias_se})"),
      #`B/S%` = `b/s%`,
      SD = str_glue("{sd} ({sd_se})"),
      #`SD%` = `sd%`,
      RMSE = str_glue("{rmse} ({rmse_se})"),
      CP = str_glue("{cp} ({cp_se})"),
      Length = str_glue("{length} ({length_se})"),
      #`L%` = round(`length%`), 
      #`$\\hat{s}$` = round(shat),
      .keep = "none",
      .before = everything()
    )
})

tab %>% 
  kbl(
    label = lab, caption = cap, centering = T,  booktabs = T, linesep = "",
    align = c(rep("c", 3), rep("r", ncol(tab) - 3)),
    position = "H", escape = F
  ) %>%
  kable_styling() %>% 
  row_spec(0, align = "c") %>% 
  column_spec(1, width = "1.4cm") %>% 
  collapse_rows(columns = 1, latex_hline = "none") %>% 
  row_spec(n_method, hline_after = T) %>% 
  row_spec(n_method * 2, hline_after = T) %>% 
  row_spec(n_method * 3, hline_after = T) %>% 
  row_spec(n_method * 4, hline_after = T) %>% 
  footnote(general = ft, general_title = "", threeparttable = T)
```




```{r tab:sim_bias_400_2, results='asis'}
supp_name <- "bias"
lab <- str_glue("sim_{supp_name}_400_2")
cap <- str_glue("Simulation results for OLS, Lasso, and Lasso + OLS, when $s=400$.")
ft <- "Note: The numbers in brackets are the corresponding standard errors estimated using the bootstrap with 500 replications. Bias, SD, RMSE, CP, Length, and their standard errors are multiplied by 100."
n_method <- 8

load(str_glue("../data/setups_dense.RData"))

# .x <- 2
tab <- map_dfr(24:27, ~{
  load(file = str_glue("../output/{supp_name}_sum_c{.x}.RData"))
  sum_tab %>% 
    left_join(setups, by = "case") %>% 
    filter(s == 400) %>% 
    arrange(estimator) %>% 
    mutate(
      bias = sprintf("%.3f", round(bias * 100, 3)),
      across(c(sd, rmse, cp, length), ~ sprintf("%.1f", round(.x * 100, 1))),
      across(ends_with("_se") & !bias_se, ~ sprintf("%.1f", round(.x * 100, 1))),
      across(bias_se, ~ sprintf("%.3f", round(.x * 100, 3)))
    ) %>% 
    mutate(
      Scenario = case_when(
        strata == "none" & propensity == "eq" ~ "No block",
        strata == "several large coarse" & propensity == "eq" ~ "Large, equal",
        strata == "several large coarse" & propensity == "uneq" ~ "Large, unequal",
        strata == "many small coarse" & propensity == "eq" ~ "Small, equal",
        strata == "many small coarse" & propensity == "uneq" ~ "Small, unequal",
        strata == "hybrid coarse" & propensity == "eq" ~ "Hybrid, equal",
        strata == "hybrid coarse" & propensity == "uneq" ~ "Hybrid, unequal",
        strata == "triplet" & propensity == "eq" ~ "Triplet, equal",
        strata == "triplet" & propensity == "uneq" ~ "Triplet, unequal"
      ),
      `Rerand.` = rerand, 
      `Est.` = fct_recode(estimator, lasso = "lasso.1se", "lasso+ols" = "lasso+ols.1se"),
      Bias = str_glue("{bias} ({bias_se})"),
      #`B/S%` = `b/s%`,
      SD = str_glue("{sd} ({sd_se})"),
      #`SD%` = `sd%`,
      RMSE = str_glue("{rmse} ({rmse_se})"),
      CP = str_glue("{cp} ({cp_se})"),
      Length = str_glue("{length} ({length_se})"),
      #`L%` = round(`length%`), 
      #`$\\hat{s}$` = round(shat),
      .keep = "none",
      .before = everything()
    )
})

tab %>% 
  kbl(
    label = lab, caption = cap, centering = T,  booktabs = T, linesep = "",
    align = c(rep("c", 3), rep("r", ncol(tab) - 3)),
    position = "H", escape = F
  ) %>%
  kable_styling() %>% 
  row_spec(0, align = "c") %>% 
  column_spec(1, width = "1.4cm") %>% 
  collapse_rows(columns = 1, latex_hline = "none") %>% 
  row_spec(n_method, hline_after = T) %>% 
  row_spec(n_method * 2, hline_after = T) %>% 
  row_spec(n_method * 3, hline_after = T) %>% 
  footnote(general = ft, general_title = "", threeparttable = T)
```

# S4_sim_lambda

 
```{r fig:sim_lambda_40, fig.width=12, fig.height=6, fig.show = 'asis'}
supp_name <- "lambda"
lab <- str_glue("sim_{supp_name}_40")
cap <- str_glue("Simulation results for different $lambda$, when $s=40$.")
ft <- "Note: The numbers in brackets are the corresponding standard errors estimated using the bootstrap with 500 replications. Bias, SD, RMSE, CP, Length, and their standard errors are multiplied by 100."

load(str_glue("../data/setups_dense.RData"))

# .x <- 2
tab <- map_dfr(1:9, ~{
  load(file = str_glue("../output/{supp_name}_sum_c{.x}.RData"))
  sum_tab %>% 
    left_join(setups, by = "case") %>% 
    filter(s == 40) %>% 
    # arrange(estimator) %>% 
    # mutate(
    #   across(c(bias, sd, rmse, cp, length), ~ sprintf("%.1f", round(.x * 100, 1))),
    #   across(ends_with("_se"), ~ sprintf("%.1f", round(.x * 100, 1))),
    # ) %>% 
    mutate(
      Scenario = case_when(
        strata == "none" & propensity == "eq" ~ "No block",
        strata == "several large coarse" & propensity == "eq" ~ "Large, equal",
        strata == "several large coarse" & propensity == "uneq" ~ "Large, unequal",
        strata == "many small coarse" & propensity == "eq" ~ "Small, equal",
        strata == "many small coarse" & propensity == "uneq" ~ "Small, unequal",
        strata == "hybrid coarse" & propensity == "eq" ~ "Hybrid, equal",
        strata == "hybrid coarse" & propensity == "uneq" ~ "Hybrid, unequal",
        strata == "triplet" & propensity == "eq" ~ "Triplet, equal",
        strata == "triplet" & propensity == "uneq" ~ "Triplet, unequal"
      ),
      `Rerand` = rerand, 
      `Estimator` = estimator,
      # Bias = str_glue("{bias} ({bias_se})"),
      Bias = bias,
      `B/S%` = `b/s%`,
      #SD = str_glue("{sd} ({sd_se})"),
      SD = sd,
      `SD%` = `sd%`,
      #RMSE = str_glue("{rmse} ({rmse_se})"),
      RMSE = rmse,
      #CP = str_glue("{cp} ({cp_se})"),
      CP = cp,
      #Length = str_glue("{length} ({length_se})"),
      Length = length,
      `L%` = round(`length%`), 
      Lambda = lambda,
      shat = round(shat),
      .keep = "none",
      .before = everything()
    )
}) %>% mutate(Scenario = as_factor(Scenario))

p1 <- tab %>% 
  ggplot(aes(x = Lambda, y = RMSE)) +
  geom_hline(
    data = . %>% group_by(Scenario, Rerand) %>% summarise(low = min(RMSE), .groups = "drop"),
    aes(yintercept = low), linetype = 2
  ) +
  geom_line() +
  geom_point(data = . %>% filter(Estimator == "lasso.1se"), color = "red") +
  facet_grid(Rerand ~ Scenario, labeller = labeller(.rows = label_both, .cols = label_value), scales = "free_x") +
  xlab(latex2exp::TeX("$\\lambda$"))
ggsave(filename = "sim_lambda_40_rmse.pdf", width = 12, height = 6)


p2 <- tab %>% 
  ggplot(aes(x = Lambda, y = Length)) +
  geom_hline(
    data = . %>% group_by(Scenario, Rerand) %>% summarise(low = min(Length), .groups = "drop"),
    aes(yintercept = low), linetype = 2
  ) +
  geom_line() +
  geom_point(data = . %>% filter(Estimator == "lasso.1se"), color = "red") +
  facet_grid(Rerand ~ Scenario, labeller = labeller(.rows = label_both, .cols = label_value), scales = "free_x") +
  xlab(latex2exp::TeX("$\\lambda$"))
ggsave(filename = "sim_lambda_40_length.pdf", width = 12, height = 6)

p3 <- tab %>% 
  ggplot(aes(x = Lambda, y = CP)) +
  geom_hline(yintercept = 0.95, linetype = 2) +
  geom_line() +
  geom_point(data = . %>% filter(Estimator == "lasso.1se"), color = "red") +
  facet_grid(Rerand ~ Scenario, labeller = labeller(.rows = label_both, .cols = label_value), scales = "free_x") +
  xlab(latex2exp::TeX("$\\lambda$"))
ggsave(filename = "sim_lambda_40_cp.pdf", width = 12, height = 6)

cowplot::plot_grid(
    p1,
    p2,
    p3,
    ncol = 1,
    align = "hv"
  )
ggsave(filename = "sim_lambda_40.pdf", width = 12, height = 12)
```




# S5_sim_heter

```{r tab:sim_heter, results='asis'}
supp_name <- "heter"
lab <- str_glue("sim_{supp_name}")
cap <- str_glue("Simulation results for block-specific coefficients.")
ft <- "Note: The numbers in brackets are the corresponding standard errors estimated using the bootstrap with 500 replications. Bias, SD, RMSE, CP, Length, and their standard errors are multiplied by 100."
n_method <- 4

load(str_glue("../data/setups_{supp_name}.RData"))

# .x <- 1
tab <- map_dfr(1:9, ~{
  load(file = str_glue("../output/{supp_name}_sum_c{.x}.RData"))
  sum_tab %>% 
    left_join(setups, by = "case") %>% 
    arrange(estimator) %>% 
    mutate(
      across(c(bias, sd, rmse, cp, length), ~ sprintf("%.1f", round(.x * 100, 1))),
      across(ends_with("_se"), ~ sprintf("%.1f", round(.x * 100, 1))),
    ) %>% 
    mutate(
      Scenario = case_when(
        strata == "none" & propensity == "eq" ~ "No block",
        strata == "several large coarse" & propensity == "eq" ~ "Large, equal",
        strata == "several large coarse" & propensity == "uneq" ~ "Large, unequal",
        strata == "many small coarse" & propensity == "eq" ~ "Small, equal",
        strata == "many small coarse" & propensity == "uneq" ~ "Small, unequal",
        strata == "hybrid coarse" & propensity == "eq" ~ "Hybrid, equal",
        strata == "hybrid coarse" & propensity == "uneq" ~ "Hybrid, unequal",
        strata == "triplet" & propensity == "eq" ~ "Triplet, equal",
        strata == "triplet" & propensity == "uneq" ~ "Triplet, unequal"
      ),
      `Rerand.` = rerand, 
      `Est.` = fct_recode(estimator, lasso = "lasso.1se"),
      Bias = str_glue("{bias} ({bias_se})"),
      #`B/S%` = `b/s%`,
      SD = str_glue("{sd} ({sd_se})"),
      #`SD%` = `sd%`,
      RMSE = str_glue("{rmse} ({rmse_se})"),
      CP = str_glue("{cp} ({cp_se})"),
      Length = str_glue("{length} ({length_se})"),
      #`L%` = round(`length%`), 
      #`$\\hat{s}$` = round(shat),
      .keep = "none",
      .before = everything()
    )
})

tab %>% 
  kbl(
    label = lab, caption = cap, centering = T,  booktabs = T, linesep = "",
    align = c(rep("c", 3), rep("r", ncol(tab) - 3)),
    position = "H", escape = F
  ) %>%
  kable_styling() %>% 
  row_spec(0, align = "c") %>% 
  column_spec(1, width = "1.4cm") %>% 
  collapse_rows(columns = 1, latex_hline = "none") %>% 
  row_spec(n_method, hline_after = T) %>% 
  row_spec(n_method * 2, hline_after = T) %>% 
  row_spec(n_method * 3, hline_after = T) %>% 
  row_spec(n_method * 4, hline_after = T) %>% 
  row_spec(n_method * 5, hline_after = T) %>% 
  row_spec(n_method * 6, hline_after = T) %>% 
  row_spec(n_method * 7, hline_after = T) %>% 
  row_spec(n_method * 8, hline_after = T) %>% 
  footnote(general = ft, general_title = "", threeparttable = T)
```


# S6_sim_varest

```{r tab:sim_varest, results='asis'}
supp_name <- "varest"
lab <- str_glue("sim_{supp_name}")
cap <- str_glue("Simulation results in scenarios where $Y_i(1) = Y_i(0)$ for all $i$, and our variance estimator is consistent.")
ft <- "Note: The numbers in brackets are the corresponding standard errors estimated using the bootstrap with 500 replications. Bias, SD, RMSE, CP, Length, and their standard errors are multiplied by 100."
n_method <- 4

load(str_glue("../data/setups_{supp_name}.RData"))

# .x <- 2
tab <- map_dfr(1:9, ~{
  load(file = str_glue("../output/{supp_name}_sum_c{.x}.RData"))
  sum_tab %>% 
    left_join(setups, by = "case") %>% 
    arrange(estimator) %>% 
    filter(estimator != "lasso_alt") %>% 
    mutate(
      across(c(bias, sd, rmse, cp, length), ~ sprintf("%.1f", round(.x * 100, 1))),
      across(ends_with("_se"), ~ sprintf("%.1f", round(.x * 100, 1))),
    ) %>% 
    mutate(
      Scenario = case_when(
        strata == "none" & propensity == "eq" ~ "No block",
        strata == "several large coarse" & propensity == "eq" ~ "Large, equal",
        strata == "several large coarse" & propensity == "uneq" ~ "Large, unequal",
        strata == "many small coarse" & propensity == "eq" ~ "Small, equal",
        strata == "many small coarse" & propensity == "uneq" ~ "Small, unequal",
        strata == "hybrid coarse" & propensity == "eq" ~ "Hybrid, equal",
        strata == "hybrid coarse" & propensity == "uneq" ~ "Hybrid, unequal",
        strata == "triplet" & propensity == "eq" ~ "Triplet, equal",
        strata == "triplet" & propensity == "uneq" ~ "Triplet, unequal"
      ),
      `Rerand.` = rerand, 
      `Est.` = fct_recode(estimator, lasso = "lasso.1se"),
      Bias = str_glue("{bias} ({bias_se})"),
      #`B/S%` = `b/s%`,
      SD = str_glue("{sd} ({sd_se})"),
      #`SD%` = `sd%`,
      RMSE = str_glue("{rmse} ({rmse_se})"),
      CP = str_glue("{cp} ({cp_se})"),
      Length = str_glue("{length} ({length_se})"),
      #`L%` = round(`length%`), 
      #`$\\hat{s}$` = round(shat),
      .keep = "none",
      .before = everything()
    )
})

tab %>% 
  kbl(
    label = lab, caption = cap, centering = T,  booktabs = T, linesep = "",
    align = c(rep("c", 3), rep("r", ncol(tab) - 3)),
    position = "H", escape = F
  ) %>%
  kable_styling() %>% 
  row_spec(0, align = "c") %>% 
  column_spec(1, width = "1.4cm") %>% 
  collapse_rows(columns = 1, latex_hline = "none") %>% 
  row_spec(n_method, hline_after = T) %>% 
  row_spec(n_method * 2, hline_after = T) %>% 
  row_spec(n_method * 3, hline_after = T) %>% 
  row_spec(n_method * 4, hline_after = T) %>% 
  row_spec(n_method * 5, hline_after = T) %>% 
  row_spec(n_method * 6, hline_after = T) %>% 
  row_spec(n_method * 7, hline_after = T) %>% 
  row_spec(n_method * 8, hline_after = T) %>% 
  footnote(general = ft, general_title = "", threeparttable = T)
```


# S7_sim_force


```{r tab:sim_force, results='asis'}
supp_name <- "force"
lab <- str_glue("sim_{supp_name}")
cap <- "Simulation results for forcing Lasso to adjust all covariates in $\\mathcal{K}$ by setting their corresponding $l_1$ penalties as 0."
ft <- "Note: The numbers in brackets are the corresponding standard errors estimated using the bootstrap with 500 replications. Bias, SD, RMSE, CP, Length, and their standard errors are multiplied by 100."
n_method <- 4

load(str_glue("../data/setups.RData"))

# .x <- 2
tab <- map_dfr(1:9, ~{
  load(file = str_glue("../output/{supp_name}_sum_c{.x}.RData"))
  sum_tab %>% 
    left_join(setups, by = "case") %>% 
    arrange(estimator) %>% 
    mutate(
      across(c(bias, sd, rmse, cp, length), ~ sprintf("%.1f", round(.x * 100, 1))),
      across(ends_with("_se"), ~ sprintf("%.1f", round(.x * 100, 1))),
    ) %>% 
    mutate(
      Scenario = case_when(
        strata == "none" & propensity == "eq" ~ "No block",
        strata == "several large coarse" & propensity == "eq" ~ "Large, equal",
        strata == "several large coarse" & propensity == "uneq" ~ "Large, unequal",
        strata == "many small coarse" & propensity == "eq" ~ "Small, equal",
        strata == "many small coarse" & propensity == "uneq" ~ "Small, unequal",
        strata == "hybrid coarse" & propensity == "eq" ~ "Hybrid, equal",
        strata == "hybrid coarse" & propensity == "uneq" ~ "Hybrid, unequal",
        strata == "triplet" & propensity == "eq" ~ "Triplet, equal",
        strata == "triplet" & propensity == "uneq" ~ "Triplet, unequal"
      ),
      `Rerand.` = rerand, 
      `Est.` = fct_recode(estimator, lasso = "lasso.1se", 
                          "lasso (force adj)" = "lasso (force adj).1se"),
      Bias = str_glue("{bias} ({bias_se})"),
      `B/S%` = `b/s%`,
      SD = str_glue("{sd} ({sd_se})"),
      #`SD%` = `sd%`,
      RMSE = str_glue("{rmse} ({rmse_se})"),
      CP = str_glue("{cp} ({cp_se})"),
      Length = str_glue("{length} ({length_se})"),
      #`L%` = round(`length%`), 
      #`$\\hat{s}$` = round(shat),
      .keep = "none",
      .before = everything()
    )
})

# tab %>% 
#   filter(`Rerand.` == "no", `Est.` == "lasso (force adj)") %>% 
#   pull(`SD%`) %>% 
#   range()
# 
# tab %>% 
#   filter(`Rerand.` == "yes", `Est.` == "lasso") %>% 
#   pull(`SD%`) %>% 
#   range()

tab %>% 
  kbl(
    label = lab, caption = cap, centering = T,  booktabs = T, linesep = "",
    align = c(rep("c", 3), rep("r", ncol(tab) - 3)),
    position = "H", escape = F
  ) %>%
  kable_styling() %>% 
  row_spec(0, align = "c") %>% 
  column_spec(1, width = "1.4cm") %>% 
  collapse_rows(columns = 1, latex_hline = "none") %>% 
  row_spec(n_method, hline_after = T) %>% 
  row_spec(n_method * 2, hline_after = T) %>% 
  row_spec(n_method * 3, hline_after = T) %>% 
  row_spec(n_method * 4, hline_after = T) %>% 
  row_spec(n_method * 5, hline_after = T) %>% 
  row_spec(n_method * 6, hline_after = T) %>% 
  row_spec(n_method * 7, hline_after = T) %>% 
  row_spec(n_method * 8, hline_after = T) %>% 
  footnote(general = ft, general_title = "", threeparttable = T)
```

# S8_sim_power

```{r tab:sim_power, results='asis'}
supp_name <- "power"
scenario_seq <- rep(c("No block", "Large, equal", "Large, unequal", "Small, equal",
                   "Small, unequal","Hybrid, equal", "Hybrid, unequal", "Triplet, equal",
                   "Triplet, unequal"), 2)

tab <- map_dfr(1:9, ~ {
  load(file = str_glue("../output/{supp_name}_sum_c{.x}.RData"))
  sum_tab2 %>%
    arrange(estimator) %>%
    mutate(Scenario = scenario_seq[.x], Power = power) %>% 
    mutate(
      Method = as_factor(case_when(
        rerand == "no" & estimator == "unadj"  ~ "unadj",
        rerand == "yes" & estimator == "unadj"  ~ "rerand+unadj",
        rerand == "no" & estimator == "lasso.1se"  ~ "lasso",
        rerand == "yes" & estimator == "lasso.1se"  ~ "rerand+lasso"
      ))
    ) %>% 
    select(Scenario, Method, tau, Power)
}) %>% 
  mutate(Scenario = as_factor(Scenario))

tab %>%
  ggplot(aes(x= tau, y = Power, color = Method)) +
  geom_hline(yintercept = 0.05, linewidth = 0.4, linetype = 2) +
  geom_line() +
  #geom_point() +
  xlab(TeX("$\\tau$")) +
  facet_wrap(vars(Scenario)) +
  theme(legend.position = "bottom")

ggsave(filename = "sim_power.pdf", width = 8, height = 10)
```

