---
output: 
  pdf_document:
    keep_tex: yes
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = TRUE)
library(tidyverse)
library(kableExtra)
library(latex2exp)
library(viridis)
theme_set(theme_bw())
scenario_name <- c(
  "No block", "Large, equal", "Large, unequal", "Small, equal", "Small, unequal",
  "Hybrid, equal", "Hybrid, unequal", "Triplet, equal", "Triplet, unequal"
)
```

## sim

```{r tab:sim_300, results='asis'}
load("../data/setups.RData")

# .x <- 1
res1 <- map_dfr(1:9, ~{
  load(file = str_glue("../output/sum_c{.x}.RData"))
  sum_tab %>% 
    left_join(setups, by = "case") %>% 
    filter(estimator %in% c("unadj", "lasso.1se")) %>% 
    mutate(estimator = fct_recode(estimator, lasso = "lasso.1se")) %>% 
    mutate(
      Scenario = scenario_name[case],
      across(c(bias, sd, rmse, cp, length), ~ sprintf("%.1f", round(.x * 100, 1))),
      across(ends_with("_se"), ~ sprintf("%.1f", round(.x * 100, 1))),
      bias = str_glue("{bias} ({bias_se})"),
      sd = str_glue("{sd} ({sd_se})"),
      rmse = str_glue("{rmse} ({rmse_se})"),
      cp = str_glue("{cp} ({cp_se})"),
      length = str_glue("{length} ({length_se})")
    ) %>% 
    select(Scenario, rerand, estimator, bias, sd, rmse, cp, length) %>% 
    arrange(estimator) %>% 
    rename(
      `Rerand.` = rerand, `Est.` = estimator, Bias = bias, SD = sd, RMSE = rmse, 
      CP = cp, Length = length
    )
}) %>% mutate(Scenario = as_factor(Scenario))

res1 %>% 
  kbl(
    caption = str_glue("Simulation results for different stratification types and equal or unequal propensity scores when $n=300$."),
    label = str_glue("sim_300"),
    centering = T, 
    booktabs = T, 
    linesep = "",
    position = "p",
    align = c(rep("c", 3), rep("r", 5))
  ) %>%
  kable_styling() %>% 
  row_spec(0, align = "c") %>% 
  column_spec(1, width = "1.4cm") %>% 
  collapse_rows(columns = 1, latex_hline = "none") %>% 
  row_spec(4, hline_after = T) %>% 
  row_spec(8, hline_after = T) %>% 
  row_spec(12, hline_after = T) %>% 
  row_spec(16, hline_after = T) %>% 
  row_spec(20, hline_after = T) %>% 
  row_spec(24, hline_after = T) %>% 
  row_spec(28, hline_after = T) %>% 
  row_spec(32, hline_after = T) %>% 
  footnote(
    general = "Note: The numbers in brackets are the corresponding standard errors estimated using the bootstrap with 500 replications. Bias, SD, RMSE, CP, Length, and their standard errors are multiplied by 100.", general_title = "", threeparttable = T
  )

```


```{r tab:sim_600, results='asis'}
# .x <- 1
res2 <- map_dfr(10:18, ~{
  load(file = str_glue("../output/sum_c{.x}.RData"))
  sum_tab %>% 
    left_join(setups, by = "case") %>% 
    filter(estimator %in% c("unadj", "lasso.1se")) %>% 
    mutate(estimator = fct_recode(estimator, lasso = "lasso.1se")) %>% 
    mutate(
      Scenario = scenario_name[case - 9],
      across(c(bias, sd, rmse, cp, length), ~ sprintf("%.1f", round(.x * 100, 1))),
      across(ends_with("_se"), ~ sprintf("%.1f", round(.x * 100, 1))),
      bias = str_glue("{bias} ({bias_se})"),
      sd = str_glue("{sd} ({sd_se})"),
      rmse = str_glue("{rmse} ({rmse_se})"),
      cp = str_glue("{cp} ({cp_se})"),
      length = str_glue("{length} ({length_se})")
    ) %>% 
    select(Scenario, rerand, estimator, bias, sd, rmse, cp, length) %>% 
    arrange(estimator) %>% 
    rename(
      `Rerand.` = rerand, `Est.` = estimator, Bias = bias, SD = sd, RMSE = rmse, 
      CP = cp, Length = length
    )
})

res2 %>% 
  kbl(
    caption = str_glue("Simulation results for different stratification types and equal or unequal propensity scores when $n=600$."),
    label = str_glue("sim_600"),
    centering = T, 
    booktabs = T, 
    linesep = "",
    position = "p",
    align = c(rep("c", 3), rep("r", 5))
  ) %>%
  kable_styling() %>% 
  row_spec(0, align = "c") %>% 
  column_spec(1, width = "1.4cm") %>% 
  collapse_rows(columns = 1, latex_hline = "none") %>% 
  row_spec(4, hline_after = T) %>% 
  row_spec(8, hline_after = T) %>% 
  row_spec(12, hline_after = T) %>% 
  row_spec(16, hline_after = T) %>% 
  row_spec(20, hline_after = T) %>% 
  row_spec(24, hline_after = T) %>% 
  row_spec(28, hline_after = T) %>% 
  row_spec(32, hline_after = T) %>% 
  footnote(
    general = "Note: The numbers in brackets are the corresponding standard errors estimated using the bootstrap with 500 replications. Bias, SD, RMSE, CP, Length, and their standard errors are multiplied by 100.", general_title = "", threeparttable = T
  )

```


```{r fig:sim_dist300, include=FALSE}
# .x <- 1
scenario_seq <- rep(c("No block", "Large, equal", "Large, unequal", "Small, equal",
                   "Small, unequal","Hybrid, equal", "Hybrid, unequal", "Triplet, equal",
                   "Triplet, unequal"), 2)

res <- map_dfr(1:18, ~ {
  load(file = str_glue("../output/result/inf_c{.x}.RData"))
  inf_tab %>%
    left_join(setups, by = "case") %>%
    filter(estimator %in% c("unadj", "lasso.1se")) %>%
    arrange(estimator) %>%
    mutate(
      Scenario = scenario_seq[case],
      Method = as_factor(case_when(
        rerand == "no" & estimator == "unadj"  ~ "unadj",
        rerand == "yes" & estimator == "unadj"  ~ "rerand+unadj",
        rerand == "no" & estimator == "lasso.1se"  ~ "lasso",
        rerand == "yes" & estimator == "lasso.1se"  ~ "rerand+lasso"
      )),
      tauhat_c = tauhat - setups$tau[.x]
    ) %>%
    select(n, Scenario, Method, tauhat_c)
  }) %>%
  mutate(Scenario = as_factor(Scenario), n = as_factor(str_glue("n = {n}"))) %>%
  select(n, Scenario, Method, tauhat_c)

# # check
# res %>%
#   group_by(n, Scenario, Method) %>%
#   summarise(bias = round(mean(tauhat_c) * 100, 1))

res %>%
  filter(n == "n = 300") %>%
  ggplot(aes(x = Method, y = tauhat_c)) +
  geom_violin(size = 0.4, scale = "width") +
  geom_hline(yintercept = 0, size = 0.4, linetype = 2) +
  facet_wrap(vars(Scenario)) +
  theme(axis.text.x = element_text(angle = 30, vjust = 1, hjust = 1)) +
  ylab(TeX("$\\hat{\\tau} - \\tau$"))
ggsave(filename = "sim_dist300.pdf", width = 10, height = 6)
```


```{r fig:sim_dist600, include=FALSE}
# # .x <- 1
scenario_seq <- rep(c("No block", "Large, equal", "Large, unequal", "Small, equal",
                   "Small, unequal","Hybrid, equal", "Hybrid, unequal", "Triplet, equal",
                   "Triplet, unequal"), 2)

res <- map_dfr(1:18, ~ {
  load(file = str_glue("../output/result/inf_c{.x}.RData"))
  inf_tab %>%
    left_join(setups, by = "case") %>%
    filter(estimator %in% c("unadj", "lasso.1se")) %>%
    arrange(estimator) %>%
    mutate(
      Scenario = scenario_seq[case],
      Method = as_factor(case_when(
        rerand == "no" & estimator == "unadj"  ~ "unadj",
        rerand == "yes" & estimator == "unadj"  ~ "rerand+unadj",
        rerand == "no" & estimator == "lasso.1se"  ~ "lasso",
        rerand == "yes" & estimator == "lasso.1se"  ~ "rerand+lasso"
      )),
      tauhat_c = tauhat - setups$tau[.x]
    ) %>%
    select(n, Scenario, Method, tauhat_c)
  }) %>%
  mutate(Scenario = as_factor(Scenario), n = as_factor(str_glue("n = {n}"))) %>%
  select(n, Scenario, Method, tauhat_c)

# # check
# res %>%
#   group_by(n, Scenario, Method) %>%
#   summarise(bias = round(mean(tauhat_c) * 100, 1))

res %>%
  filter(n == "n = 600") %>%
  ggplot(aes(x = Method, y = tauhat_c)) +
  geom_violin(size = 0.4, scale = "width") +
  geom_hline(yintercept = 0, size = 0.4, linetype = 2) +
  facet_wrap(vars(Scenario)) +
  theme(axis.text.x = element_text(angle = 30, vjust = 1, hjust = 1)) +
  ylab(TeX("$\\hat{\\tau} - \\tau$"))
ggsave(filename = "sim_dist600.pdf", width = 10, height = 6)
```


```{r sim compare, echo=TRUE}
res <- map_dfr(1:18, ~{
  load(file = str_glue("../output/sum_c{.x}.RData"))
  sum_tab %>% 
    filter(estimator %in% c("unadj", "lasso.1se")) %>% 
    summarise(
      sd_red = round((1 - sd[4] / sd[1]) * 100),
      l_red = round((1 - length[4] / length[1]) * 100)
    )
})
res$sd_red %>% range
res$l_red %>% range
```





## rd


```{r tab:rd, results='asis'}
# .x <- 1
res <- map_dfr(1:2, ~{
  load(file = str_glue("../output/rd_sum_c{.x}.RData"))
  if (.x == 1) {
    sum_tab_sel <- sum_tab %>% 
      filter(estimator %in% c("unadj", "lasso.rmin/60")) %>% 
      mutate(estimator = fct_recode(estimator, lasso = "lasso.rmin/60"))
  } else {
    sum_tab_sel <- sum_tab %>% 
      filter(estimator %in% c("unadj", "lasso.1se"), rerand == "no") %>% 
      mutate(estimator = fct_recode(estimator, lasso = "lasso.1se"), rerand = "-")
  }
  sum_tab_sel %>% 
    mutate(
      across(c(bias, sd, rmse, cp, length), ~ sprintf("%.2f", round(.x * 100, 2))),
      across(ends_with("_se"), ~ sprintf("%.2f", round(.x * 100, 2))),
      bias = str_glue("{bias} ({bias_se})"),
      sd = str_glue("{sd} ({sd_se})"),
      rmse = str_glue("{rmse} ({rmse_se})"),
      cp = str_glue("{cp} ({cp_se})"),
      length = str_glue("{length} ({length_se})")
    ) %>% 
    select(rerand, estimator, bias, sd, rmse, cp, length) %>% 
    arrange(estimator) %>% 
    rename(
      `Rerand.` = rerand, `Est.` = estimator, Bias = bias, SD = sd, RMSE = rmse, 
      CP = cp, Length = length
    )
})


res %>% 
  kbl(
    caption = str_glue("Simulation results for two semi-sythetic data sets"),
    label = str_glue("rd"),
    centering = T, 
    booktabs = T, 
    linesep = "",
    position = "p",
    align = c(rep("c", 2), rep("r", 5))
  ) %>%
  kable_styling() %>% 
  row_spec(0, align = "c") %>% 
  pack_rows("OK data", 1, 4, latex_align = "c", escape = F) %>%
  pack_rows("Fish data", 5, 6, latex_align = "c", escape = F) %>%
  row_spec(4, hline_after = T) %>% 
  footnote(
    general = "Note: The numbers in brackets are the corresponding standard errors estimated using the bootstrap with 500 replications. Bias, SD, RMSE, CP, Length, and their standard errors are multiplied by 100.", general_title = "", threeparttable = T
  )

```





```{r rd1 info, echo=TRUE}
library(glmnet)
source("../stra.R")
load("../data/ok.RData")

dt_final %>% 
  count(B) %>% 
  arrange(n)

dt_final %>% 
  group_by(B) %>% 
  count(Z)

dt_final %>% 
  select(where(
    ~ attr(.x, "label") %in% c("predictor")
  )) %>% 
  dim

dt_final %>% 
  select(where(
    ~ attr(.x, "label") %in% c("predictor", "quadratic", "interaction")
  )) %>% 
  dim

set.seed(2022)
(fit <- stra_adj(dt_final$Y, dt_final$Z, B, X, "lasso", "min", s_res = 1/60,
                 return_Sz = T))

rbind(
  stra_unadj(dt_final$Y, dt_final$Z, B, p_a = 1),
  fit$inf_res
) %>% mutate(
  length = ci_u - ci_l,
  across(c("tauhat", "ci_l", "ci_u"), ~ round(., 3)),
  `l%` = round((1 - length[2] / length[1]) * 100)
)


load(file = str_glue("../output/rd_sum_c1.RData"))
sum_tab %>% 
  filter(estimator %in% c("unadj", "lasso.rmin/60")) %>% 
  summarise(
    `sd%` = round((1 - sd[4] / sd[1]) * 100),
    `l%` = round((1 - length[4] / length[1]) * 100)
  )
```



```{r rd2 info, echo=TRUE}
library(glmnet)
source("../stra.R")
load("../data/fish.RData")

dt_final %>% 
  count(B) %>% 
  arrange(n)

dt_final %>% 
  group_by(B) %>% 
  count(Z)

dt_final %>% 
  select(where(
    ~ attr(.x, "label") %in% c("predictor")
  )) %>% 
  dim

dt_final %>% 
  select(where(
    ~ attr(.x, "label") %in% c("predictor", "quadratic", "interaction")
  )) %>% 
  dim

set.seed(2022)
(fit <- stra_adj(dt_final$Y, dt_final$Z, B, X, "lasso", "1se", return_Sz = T))

rbind(
  stra_unadj(dt_final$Y, dt_final$Z, B, p_a = 1),
  fit$inf_res
) %>% mutate(
  length = ci_u - ci_l,
  across(c("tauhat", "ci_l", "ci_u"), ~ round(., 3)),
  `l%` = round((1 - length[2] / length[1]) * 100)
)


load(file = str_glue("../output/rd_sum_c2.RData"))
sum_tab %>% 
  filter(estimator %in% c("unadj", "lasso.1se")) %>% 
  summarise(
    `sd%` = round((1 - sd[4] / sd[1]) * 100),
    `l%` = round((1 - length[4] / length[1]) * 100)
  )
```





